---
- ignore:
    name: "Avoid lambda"
    within:
      - "Effectful.FileSystem.PathWriter.Utils"
      - "Effectful.LoggerNS.Utils"
      - "Effectful.Time.TimeSpec"

- ignore:
    name: "Avoid lambda using `infix`"
