name: ci

on:
  push:
    branches:
      - main
      - env-static

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  cabal:
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - "8.10.7"
          - "9.0.2"
          - "9.2.8"
          - "9.4.6"
          - "9.6.2"
        os:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure
        run: cabal configure --enable-tests

      - name: Compile
        run: cabal build all

      - name: Test fs-effectful
        run: cabal test fs-effectful --test-options '--hedgehog-tests 100000'

      - name: Test logger-ns-effectful
        run: cabal test logger-ns-effectful

      - name: Test time-effectful
        run: cabal test time-effectful --test-options '--hedgehog-tests 100000'
  nix:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/897876e4c484f1e8f92009fd11b7d988a121a4e7.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build & Test
        run: |
          nix build \
            .#concurrent-effectful \
            .#env-guard-effectful \
            .#environment-effectful \
            .#exceptions-effectful \
            .#fs-effectful \
            .#ioref-effectful \
            .#logger-effectful \
            .#logger-ns-effectful \
            .#optparse-effectful \
            .#stm-effectful \
            .#terminal-effectful \
            .#time-effectful \
            .#typed-process-dynamic-effectful \
            .#unix-compat-effectful

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Setup nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/897876e4c484f1e8f92009fd11b7d988a121a4e7.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Formatting
        run: |
          nix run .#format
          git diff --exit-code --color=always

      - name: HLint
        run: nix run .#lint
